### ISSUE TITLE
p_value of X?

### ISSUE THREAD

**Issue by Dawn0502** [jean997/cause#12]
Hi,
I merged the X as the instruction in the tutorial. And when I perform step 3: LD pruning with these code:

`X_clump <- IntelandICV %>% rename(rsid = snp) %>%
 ieugwasr::ld_clump(dat = .,
 clump_r2 = r2_thresh,
  clump_p = pval_thresh,
 plink_bin = genetics.binaRies::get_plink_binary(),
  bfile = ref_path)
`

The result returned an error
Error: Can't rename columns that don't exist.
x Column `p_value` doesn't exist.
I was confused that if this p_value belongs to the merged dataset X or something else? 

Thanks for all your help!

Best Regards,
Dawn

**Comment by jean997** [comment]
Hi Dawn,
I'm sorry I missed this issue, I hope you got it figured out.

 It looks like an error with the ld_clump function in ieugwasr which expects specific column names for p-value. Here is the reference for that function:
https://mrcieu.github.io/ieugwasr/reference/ld_clump.html
I find the error weird because the ld_clump expects your p-value column to be called "pval" not "p_value"
The error about not renaming columns that don't exist suggests that `IntelandICV` doesn't have a column named `snp`. 
Jean
