### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by adamber6** [jean997/cause#33]
I am sorry to bother you.
When I perform CAUSE analysis, there are issues in this step:
top_vars <-ieugwasr::ld_clump(dat =for_clump,clump_p=1e-3)
Please look at vignettes for options on running this locally if you need to run many instances of this command.
Clumping F69fg2, 211 variants, using EUR population reference
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server code: 503; Server is possibly experiencing traffic, trying again...
Server error: 503
Failed to retrieve results from server. See error status message in the returned object and contact the developers if the problem persists.
Removing 211 of 211 variants due to LD with other variants or absence from LD reference panel.

Can you tell me how solve this problem?
Thank you very much.
Best regards.

**Comment by jean997** [comment]
This problem is caused because the IEU server is getting too many requests. You can solve the problem by LD clumping using local data instead of querying the database for it. 

See here for instructions: https://mrcieu.github.io/ieugwasr/articles/local_ld.html

All you need to do is download the bim/bed/fam files and then provide an argument to ld_clump. You will also need a local version of plink. 

Jean
