### ISSUE TITLE
Presentation and Interpretation of Results

### ISSUE THREAD

**Issue by nadineparker** [jean997/cause#34]
Hi Jean,
I don't have an issue with the code but more of a question about the presentation and interpretation of the results. I've noticed that some papers that use the CAUSE MR method report the gamma estimate as the causal effect estimate similar to the beta in other MR methods. Some others plot this estimate as an OR with associated 95% confidence intervals. While some papers simply present the p-value comparing the causal model to the sharing model. I wondered what your thoughts are on the best way to present CAUSE results and interpret the gamma parameter?

**Comment by jean997** [comment]
Hi - good question. 

We view the posterior distribution of gamma as the estimate of the causal effect. The interval associated with gamma is a credible interval. The units of the causal effect depend on what kind of summary statistics you use. If the associations with the outcome were measured on the log odds scale and the associations with the exposure are measured on the linear scale, then gamma will also be on the log odds scale. If you believe the model that log odds of Y is linear in X then the MR estimate (gamma in CAUSE) is estimating the marginal log odds ratio for a one unit change in X. Here marginal means marginal over all other covariates and over the instruments. 

There is quite a bit of discussion in recent (and older) literature about interpretations of MR causal effect estimates. The limitations (for all MR methods, not only CAUSE) are that clean causal interpretations require a) parametric assumptions about the relationship between X and Y b) a clearly defined single exposure that is instrumented by the variants. In MR we don't usually have (b) even if we are willing to make the parametric assumptions. The reason is that different variants may affect slightly different "versions" of the trait, for example early in life or late in life exposure, or exposure in different tissues etc. I don't think this means that MR estimates are useless but it does lead to some tempering of how we interpret the size of the estimate. Under much weaker assumptions, MR is still a good test of the causal null and gives a valid estimate of the direction of the average causal effect if we make some weaker assumptions that the contributions of the "component exposures" are all in the same direction or null for everyone. I think that if you are careful about how you scale the exposure associations, MR estimates can also give an idea of the relative size of causal effects for different exposures. 

All this is to say, to me the most useful pieces of information from CAUSE are the direction of the causal effect (gamma) and the credible interval which tells us how confident we are in the sign of the effect. The p-value is useful if you want to do model selection (i.e. decide yes/no on following up a potential causal effect). I don't like over-reliance on p-values though I do know that p-value based decision making is standard in the MR field which is why we decided to provide one. Secondarily, the estimate of the confounding effect may be useful, especially if you have some idea about the source of potential confounding.

**Comment by nadineparker** [comment]
Thank you Jean! This was very informative and helpful. I appreciate it.
